#!/bin/sh

#
# 2021-09-09 Moved from /etc/init.d to /media/fat/tty2oled 
# 2021-01-22 Added -x /usr/bin/tty2oled check to start()
# 2021-04-12 Added an INI file
#

. /media/fat/tty2oled/tty2oled.ini

# Start
start() {
    ### Wait for USB module and start tty2oled daemon
    WAITEND=$((SECONDS+10))
    while !  [ -c ${TTYDEV} ] && [ ${SECONDS} -lt ${WAITEND} ]; do
      sleep 0.1
    done

    if [[ -x ${DAEMONSCRIPT} ]]; then
      echo "Starting ${DAEMONNAME}..."
      ${DAEMONSCRIPT} &
    else
      echo "${DAEMONSCRIPT} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping ${DAEMONNAME}..."
    killall ${DAEMONNAME}
}

case "$1" in
  start)
        start
        ;;
  stop) 
        stop
        ;;
  restart)
        stop
        start
        ;;
#  reload)
#       reload
#       ;;
  *)
#        echo "Usage: $0 {start|stop|restart|reload}"
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
