#!/bin/sh

#
# 2021-01-22 Added -x /usr/bin/tty2oled check to start()
# 2021-04-12 Added an INI file
#

. /media/fat/Scripts/tty2oled.ini

# Start
start() {
    if [[ -x ${DAEMONSCRIPT} ]]; then
      echo "Starting tty2oled..."
      ${DAEMONSCRIPT} &
    else
      echo "${DAEMONSCRIPT} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping tty2oled..."
    killall tty2oled
}

case "$1" in
  start)
        start
        ;;
  stop) 
        stop
        ;;
  restart)
        stop
        start
        ;;
#  reload)
#       reload
#       ;;
  *)
#        echo "Usage: $0 {start|stop|restart|reload}"
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
