#!/bin/bash

#
# 2022-12-13 Auto Update
# 2022-03-12 Ensure Unix-Encoding of INI files
# 2021-11-24 Working in /tmp
# 2021-09-09 Moved from /etc/init.d to /media/fat/tty2oled 
# 2021-01-22 Added -x /usr/bin/tty2oled check to start()
# 2021-04-12 Added an INI file
# 2022-06-17 Redo/Rework of PID and inotify
#

! [ "$(dos2unix -ic /media/fat/tty2oled/*.ini)" = "" ] && dos2unix -k -q /media/fat/tty2oled/*.ini
. /media/fat/tty2oled/tty2oled-system.ini
. /media/fat/tty2oled/tty2oled-user.ini

DATENOW=$(date +%s)
LASTUPDATE=$(date +%s)		# Prefill with "now"
[ -e /media/fat/tty2oled/last_update ] && read LASTUPDATE < /media/fat/tty2oled/last_update
cd /tmp

# Start
start() {
    ### Wait for USB module and start tty2oled daemon
    WAITEND=$((SECONDS+10))
    while !  [ -c ${TTYDEV} ] && [ ${SECONDS} -lt ${WAITEND} ]; do
      sleep 0.1
    done
    if ! [ -c ${TTYDEV} ]; then
      echo "Could not find the needed USB module ${TTYDEV}. Exiting."
      exit 1
    fi

    if [[ -x ${DAEMONSCRIPT} ]]; then
      if [ -e /run/tty2oled-daemon.pid ] && [ -d /proc/$(</run/tty2oled-daemon.pid) ]; then
	echo "${DAEMONNAME} already running"
	exit 1
      else
	if [ "${TTY2OLED_UPDATE}" = "yes" ] && [ "${AUTOUPDATE}" = "yes" ] && [ $((${DATENOW} - ${LASTUPDATE})) -gt 604800 ]; then
	  #echo -e "Waiting for Internet access: "
	  #until ping -W1 -c1 8.8.8.8 >/dev/null 2>&1; do echo -n "." ; sleep 0.2; done
	  #bash ${UPDATESCRIPT} NOINSTALLER > /dev/null 2>&1	# Auto Update after 1 week
	  ${TTY2OLED_PATH}/update_auto.sh &
	fi
	echo "Starting ${DAEMONNAME}..."
	${DAEMONSCRIPT} & echo $! > /run/tty2oled-daemon.pid
      fi
    else
      echo "${DAEMONSCRIPT} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping ${DAEMONNAME}..."
    if [ -e /run/tty2oled-daemon.pid ]; then
      PIDDAEMON=$(</run/tty2oled-daemon.pid)
      PIDINOTIFY=$(ps -eo pid,ppid,args | grep $(ps | grep tty2oled | awk 'NR==1{print $1}') | tail -1 | awk '{print $1}')
      #echo "PIDDAEMON = $PIDDAEMON"
      #echo "PIDINOTIFY = $PIDINOTIFY"
    fi
    [ ${PIDDAEMON} ] && kill ${PIDDAEMON} &> /dev/null
    [ ${PIDINOTIFY} ] && kill ${PIDINOTIFY} &> /dev/null
    rm -f /run/tty2oled-daemon.pid
}

case "$1" in
  start)
	start
        ;;
  stop) 
	stop
        ;;
  restart)
	stop
	start
	;;
#  reload)
#	reload
#	;;
  *)
#	 echo "Usage: $0 {start|stop|restart|reload}"
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
